#!/bin/sh
#
# Start the network....
#

case "$1" in
  start)
 	echo "Starting shell"
	#/bin/sh	/home/default/script.sh
	;;
  stop)
	echo -n "Nothing to do here"
	;;
  restart|reload)
	"$0" stop
	"$0" start
	;;
  *)
	echo "Usage: $0 {start|stop|restart}"
	exit 1
esac

exit $?

