all:
	arm-none-linux-gnueabi-gcc -Wall -O3 -static read_dyn_energy.c -o ../bin/read_dyn_energy
	arm-none-linux-gnueabi-gcc -Wall -O3 -static keep_constant_average.c -o ../bin/keep_constant_averag
	arm-none-linux-gnueabi-gcc -Wall -static mult_errors.c -o ../bin/mult_errors
	arm-none-linux-gnueabi-gcc -Wall -static mult_no_errors.c -o ../bin/mult_no_errors	
	arm-none-linux-gnueabi-gcc -Wall -O3 -static vemu_kill.c -o ../bin/vemu_kill


