all:
	arm-none-linux-gnueabi-gcc -Wall -O3 -static read_vemu_regs.c -o ../bin/read_vemu_regs
	arm-none-linux-gnueabi-gcc -Wall -static mult_errors.c -o ../bin/mult_errors
	arm-none-linux-gnueabi-gcc -Wall -static mult_no_errors.c -o ../bin/mult_no_errors	
	arm-none-linux-gnueabi-gcc -Wall -O3 -static vemu_kill.c -o ../bin/vemu_kill


