all:
	arm-none-linux-gnueabi-gcc -static read_dyn_energy.c -o ../bin/read_dyn_energy
	arm-none-linux-gnueabi-gcc -static keep_constant_average.c -o ../bin/keep_constant_averag
	arm-none-linux-gnueabi-gcc -O3 -static mult_errors.c -o ../bin/mult_errors
	arm-none-linux-gnueabi-gcc -O3 -static mult_no_errors.c -o ../bin/mult_no_errors


